Improve title of incident detail box
Uninett/Argus-frontend pull request #135
Opened 2020-09-18 07:51 UTC by hmpf

Closes #121 

It's a little odd that this part of the details box is defined in the incident table, not the incident detail box itself. Not something we should bother to fix before 1.0 though.

@lunkwill42, I've tagged you because exactly what we ought to have as the title of the box is very much up for discussion. It's very easy to change though, as long as only things stored directly on the incident are used.

2020-09-21 09:00 UTC, jorgenbele commented
The reason that it's defined in the view instead of the details component is so that the details component can be reused wherever it's useful to inline details about an incident. It is part of the dialog/modal title, not the details component, because it might not be useful to display a title and/or want it to be a dialog/modal.

2020-09-21 09:01 UTC, jorgenbele approved these changes

2020-09-23 07:58 UTC, lunkwill42 requested changes
I agree that using the Incident description as the dialog box title is much better, **however**:

1. We have no limits to how long a description may be
2. A description may even be multi-line

So to use this as title, it would need to be filtered. Suggestions:

1. If the description is multi-line, use only the first line.
2. If the description is longer than XX characters (lets pick the arbitrary number 50?), the rest should be truncated and replaced with an ellipsis...

2020-09-23 09:33 UTC, hmpf commented
Titles are now truncated, and the internal argus id is completely gone. @jorgenbele please check that the function I made is ok.

Prior to this was an octopus-merge that clobbered each other, so I fixed that too straight on master, in "Fix missing "}"". NTS: Avoid octopus-merges even more.

2020-09-23 09:38 UTC, hmpf commented
I hard-coded the length to 50 btw. where the function is used. If that constant should be somewhere else, feel free to move it @jorgenbele, because I don't know where it would belong.

2020-09-23 09:52 UTC, lunkwill42 approved these changes

2020-09-23 10:00 UTC, merged