Fix and improve filters view
Uninett/Argus-frontend pull request #161
Opened 2020-10-27 12:57 UTC by jorgenbele

This patch introduces fixes to the filter view. It
updates it to work correctly with the changes in the API
and also adds functionality for editing existing filters.

All in all this patch seems to work quite well, with
snackbar alerts used to provide the user with feedback.

Doesn't look that good, but does the job.

2020-10-27 13:02 UTC, jorgenbele commented
Closes #158 
Closes #146

2020-10-28 11:56 UTC, hmpf requested changes
Is a file missing? `src/components/filters/contexts.tsx` or something?

2020-10-28 11:56 UTC, hmpf commented on src/components/filterbuilder/FilterBuilder.tsx
> +import { FiltersContext, FiltersContextType } from "../../components/filters/contexts";
The "../../components/filters/contexts" file is not included in this commit and does not exist on master.

2020-10-28 11:56 UTC, hmpf commented on src/views/filters/FiltersView.tsx
> +import { FiltersContext, FiltersContextType, DEFAULT_FILTERS_CONTEXT_VALUE } from "../../components/filters/contexts";
The "../../components/filters/contexts" file is not included in this commit and does not exist on master.

2020-10-29 11:55 UTC, hmpf commented
I'll hand-test..

2020-10-29 13:42 UTC, hmpf reviewed
I can't make the filter-bits of this this talk to the backend properly.

2020-11-03 12:25 UTC, hmpf approved these changes
Tested and verified against backend v1.0.0.

2020-11-03 12:30 UTC, merged