Reword "Max level" to "Max severity level"
Uninett/Argus-frontend pull request #442
Opened 2022-10-11 07:34 UTC by stveit

Fixes #421

2022-10-11 14:03 UTC, podliashanyk requested changes
Short and sweet, just update NOTES.md as well 😌

2022-10-11 14:03 UTC, podliashanyk commented on CHANGELOG.md
> +- Change the label for the severity level selector from "Max level" to "Max severity level"
This one can be repeated in NOTES.md as well

2022-10-12 07:09 UTC, hmpf requested changes
Conflict in CHANGELOG, otherwise OK.

2022-10-12 11:23 UTC, podliashanyk approved these changes
👍🏻

2022-10-12 11:24 UTC, merged