Implement create ticket feature
Uninett/Argus-frontend pull request #461
Opened 2022-12-06 08:43 UTC by podliashanyk

Closes #396, #449

2022-12-06 09:21 UTC, podliashanyk commented
Remaining tasks:

- [ ] manual test against an actual ticket plugin
- [ ] tests
- [ ] update changeling

2022-12-08 09:05 UTC, podliashanyk commented
Changes requested after IRL conversation with @hmpf:

- [ ] If incident has no ticket, click on _Create Ticket_ button should:
  - [ ] fire a generate ticket event if user has not pasted any url into the input field
  - [ ] save the ticket url that user has pasted into the input field
- [ ] If incident has a ticket:
  - [ ] text in the _Ticket_ input field should be a clickable url
  - [ ] _Create Ticket_ button is changed to the _Edit ticket_ button. Click on the _Edit ticket_ button prompts a dialog where user can manually change a ticket url, or paste a new one

2022-12-09 11:51 UTC, podliashanyk commented
Currently implemented functionality:

- [ ] If incident has no ticket, click on _Create Ticket_ button:
  - [ ] fires a generate ticket event if user has not pasted any url into the input field (prompts a confirm dialog)
  - [ ] save the ticket url that user has pasted into the input field
- [ ] If incident has a ticket:
  - [ ] text in the _Ticket_ input field is a clickable url
  - [ ] _Create Ticket_ button is changed to the _Edit ticket_ button. Click on the _Edit ticket_ button make ticket field to an editable input field, and changes button text to _Save ticket_


Remaining tasks:

- [ ] Fix CSS
- [ ] Fix failing tests
- [ ] Write more tests
- [ ] Update changelog

2022-12-15 11:47 UTC, hmpf requested changes
This new feature is not mentioned in MANUAL.md. We could punt that to another PR, but then we should have an issue about it so we don't forget it.

2022-12-15 11:47 UTC, hmpf commented on src/state/hooks.tsx
>  };
Meep-meep, maybe we should have pre-commit add missing newlines?

2022-12-15 11:47 UTC, hmpf commented on src/state/reducers/ticketurl.ts
> +export const resetTicketState = makeAction<TicketType.ResetTicketState, string | undefined | null>(TicketType.ResetTicketState);
Another missing newline.

2022-12-15 13:03 UTC, hmpf approved these changes

2022-12-15 13:10 UTC, merged