Add destinations to notification profiles
Uninett/Argus-frontend pull request #479
Opened 2023-02-01 07:26 UTC by podliashanyk

2023-02-01 10:28 UTC, johannaengland requested changes
After creating a profile the linked destinations are all shown only by their suggested label even if they have a user-set label. I would expect to see the user-set label there as well.

2023-02-01 11:00 UTC, podliashanyk commented
> After creating a profile the linked destinations are all shown only by their suggested label even if they have a user-set label. I would expect to see the user-set label there as well.

Not sure about this one. I have testet different display values for the linked destinations, and IMHO suggested labels look most clear and exhaustive. But I will check with users after they have used the new profiles, and will probably conduct some user tests on different ways to display destinations in profiles

2023-02-02 07:31 UTC, hmpf commented on src/components/notificationprofile/NotificationProfileCard.test.tsx
> +  PhoneNumber,
Why is this still used, local validation?

2023-02-02 07:42 UTC, hmpf reviewed
What's with the phone numbers everywhere? Otherwise, see comments.

2023-02-02 07:42 UTC, hmpf commented on src/components/notificationprofile/NotificationProfileCard.test.tsx
> +]
There's no guarantee that the msteams plugin is installed so you can't really test it here. We might need a discussion about this.

We could have a dummy plugin that has a webhook?

2023-02-02 07:42 UTC, hmpf commented on src/components/notificationprofile/NotificationProfileList.test.tsx
> +            .onGet("/api/v2/auth/phone-number/")
I think this endpoint will go away completely. The only place phone numbers will be stored will be in destinations.

2023-02-02 09:31 UTC, podliashanyk commented
@hmpf removed phone number objects from tests. But in the notification components there is is still a _Plus_ button that prompts _Add new phone number_ dialog. So I haven't removed tests for this one yet. Switching to _Add new destination_ dialog is a separate issue #481

2023-02-02 10:08 UTC, podliashanyk commented
@johannaengland fixed overlap of sticky headers :)

2023-03-06 11:40 UTC, stveit commented on src/api/client.ts
> +  MetadataConfig, Media, Destination, MediaSchema, DestinationPK, DestinationRequest, NewDestination,
this should probably be one per line as the rest of them, looks wierd mixing it up

2023-03-08 13:28 UTC, stveit approved these changes

2023-03-09 14:15 UTC, johannaengland approved these changes
:+1:

2023-03-10 06:59 UTC, merged